{
 "title": "Cloudprober",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "probe", "label": "Probe", "query": "resp_code" }
  ]
 },
 "panels": [
  {
   "title": "$probe Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum by(probe) (rate(resp_code{probe=\"$probe\", code=~\"2..\"}[6h]))) / (sum by(probe) (rate(resp_code{probe=\"$probe\", code=~\"...\"}[6h])))) * 100"
    }
   ]
  },
  {
   "title": "$probe Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(latency{probe=\"$probe\"}[1m])) / (rate(success{probe=\"$probe\"}[1m])) / 1000"
    }
   ]
  },
  {
   "title": "$probe Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resp_code{probe=\"$probe\"}[1m])) by (probe, code)"
    }
   ]
  },
  {
   "title": "$probe Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum by(probe) (rate(resp_code{probe=\"$probe\", code=~\"2..\"}[6h]))) / (sum by(probe) (rate(resp_code{probe=\"$probe\", code=~\"...\"}[6h])))) * 100\n"
    }
   ]
  }
 ]
}