apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudprober-config
  namespace: monitoring
data:
  cloudprober.cfg: |
    probe {
      name: "pez.sh"
      type: HTTP
      targets {
        host_names: "pez.sh"
      }
      interval_msec: 5000
      timeout_msec: 1000
    }