FROM nginx:latest

COPY ./public-html/ /usr/share/nginx/html/

#RUN apt update && apt install certbot python-certbot-nginx -y
#RUN yes | certbot --nginx -d pez.sh -d www.pez.sh -m pez@pez.sh --agree-tos

EXPOSE 80