FROM nginx:1.21-alpine

COPY ./public-html/ /usr/share/nginx/html/

#RUN apk add certbot certbot-nginx

#RUN certbot --nginx -d pez.sh -d www.pez.sh -m pez@pez.sh --agree-tos --non-interactive

EXPOSE 80