apiVersion: apps/v1
kind: Deployment
metadata:
  name: pezsh
  labels:
    app: pezsh
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pezsh
  template:
    metadata:
      labels:
        app: pezsh
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pezsh
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: pezsh
        image: gcr.io/rwejlgaard/pez.sh:${SEMVER}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
#        - name: https
#          containerPort: 443