apiVersion: skaffold/v2beta11
kind: Config
build:
  googleCloudBuild:
    projectId: rwejlgaard
  artifacts:
    - image: gcr.io/rwejlgaard/netatalk
      context: src
deploy:
  kubectl:
    manifests:
      - manifests/*