apiVersion: apps/v1
kind: Deployment
metadata:
  name: pezsh
  labels:
    app: pezsh
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pezsh
  template:
    metadata:
      labels:
        app: pezsh
    spec:
      containers:
      - name: pezsh
        image: gcr.io/rwejlgaard/pez.sh
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
#        - name: https
#          containerPort: 443