apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pezsh
  namespace: web
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pezsh
  targetCPUUtilizationPercentage: 50
