{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "netatalk-secret",
    "namespace": "files",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "netatalk-secret",
        "namespace": "files",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "AFP_PASSWORD": "AgB+vf7P/G4lsI6kM2xiJD/f6jiJivEy/blY2WSorpwBJpBw4WqeDOao1tDMnu/jB6FjZyEr71Gubcm2bQyZpbHWC2n44x0MB/MJgAxPXztaCp/3HK9lT/nNZOOLfoPYEJ7UQJZ4QTZSz3mNXl++pk0dvIN+3td6EiDF8F04iqjNT8sku8XHM6IBq2Er271vyxq3fJmKVwmGbe768MoH/h6+niLv4TU5QCmxtBJYZoBg+36lXhPBooOEBXp3C/iSlFwx1kkd+xD56+9gGAItlAjpKHrYe7CLLqkShygVf/nTiBjewSmQrRblg+6Es+x1yLtMqPQ7xVAn0sqUO8OaVZ50FXeTjTLvFcSwzUuPzCKR/8m4Nl1ZwWnGcUy4mWxtaH5ejT88Bx+uOeH7S2QMOP5ixpTNcPuGs6I3guzTytNg1caSMKZNTrLqfoqOPb693hMTCpOdzjxHG/Sv+AhRDgW/5fPIxPTpOTCGtUc9rPDlsqWn37yDd5Y0FJEB0g/R/TcYC+jYHpdjIvXDOO04Jo4zl84gyS+EZ5OeEDjh7GcGIOK59Wt/2HRotD4IkP4Z5hDvAAz/Kpicq3OA1PtW54U1DBWzCNu/jddz+LBJAp9cB1TpSfAUasFqzcsjeGC6BhSmP7FClpGUpXwHQbL8mSvJfJeBjHPzBXg+kApWVy/7YeOO/22mPG2HQzCgCb8bWY0Ep61EQlUGlAI=",
      "AFP_USER": "AgDVzX3Tej+O18S+qgksyS2BiQywVnq1e96lb3CVWsvOtRr0K5Z5jOpvqmX64DcTdc5RptSvYTeubLes0T+qf1/po5Za8aw+EG6q1qxTrAfkv6WMvLKqItmzttJWbZyIA0q3p7o/JM2/UFebQT9YYnsgb/KBNVgi7SqtKf2jfXZK+VLn5ldXUohcffJQ2/0bqkytyOaks4alNkFoBWAMXl2YLGjKrk9hY9fc5O7IyGVa+VzQC9nRv0eKCwNrm9NVf9n5mQKRPIFQbDe4mmo7e8J1TD32lU3KnCPXeN19pJKtyWfcLt7VjCtPLCSEJkUsf8HpDIFugE4M4MAeIaVXGLbvFi6ajDWBnjUuyJi4ix/Vg1fBfm+Ra5hI6HNGNt+PJTaEuUiUkqpy1XKKemSNvTza1RMv2K0s2nG+s8QT71Jf3fXugCIIipW+wdDhuhYl+hf0zlF3ctS9ckW7JtVP9XxHN/Os0SOfQ59xmQnlfSDs9cU9G2DPYbiECs+W3CfqND7CL+SV8Ww0c9Rhi8QsHkYF+Q99aV7lzZV12SUnZubry/m/up6++8UmNw+HLGMJ8KZJH1PKgHq5LNkx+7PJthfjo6U2qW9dSUsETSgiHvSV9N4fl21feERgX1pxpdBNZSoQhnYThcVOlRJl22A3QRrFDTX0T9Yydrg5EQhBCRpDgmEGfVVxPoJJ1u5QXfPRrpRb70E="
    }
  }
}
