apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: gcr.io/rwejlgaard/redis
        ports:
        - containerPort: 6379
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: REDIS_PASSWORD
                name: redis-secret
        volumeMounts:
          - mountPath: /data
            name: redis-pv
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pv