# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
    route:
      receiver: 'pagerduty-notifications'

    receivers:
    - name: 'pagerduty-notifications'
      pagerduty_configs:
      - service_key: 2812063ed48b4106d0efe4669f4d45ab
        send_resolved: true
