apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: prometheus
    spec:
      containers:
#      - args:
#        - --volume-dir=/etc/config
#        - --webhook-url=http://127.0.0.1:9090/-/reload
#        image: jimmidyson/configmap-reload:v0.4.0
#        imagePullPolicy: IfNotPresent
#        name: prometheus-server-configmap-reload
#        terminationMessagePath: /dev/termination-log
#        terminationMessagePolicy: File
#        volumeMounts:
#        - mountPath: /etc/config
#          name: config-volume
#          readOnly: true
      - name: prometheus-server
        image: prom/prometheus:v2.21.0
        args:
        - --storage.tsdb.retention.time=15d
        - --config.file=/etc/config/prometheus.yml
        - --storage.tsdb.path=prom_data
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9090
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/config
            name: config-volume
          - mountPath: prom_data
            name: storage-volume
          - mountPath: pagerduty
            name: pagerduty-volume
      - name: alertmanager
        image: prom/alertmanager
        args:
          - --config.file=/etc/config/alertmanager.yml
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9091
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/config
            name: alertmanager-config-volume
      dnsPolicy: ClusterFirst
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus
        name: config-volume
      - secret:
          secretName: pagerduty-secret
        name: pagerduty-volume
      - persistentVolumeClaim:
          claimName: prometheus-pvc
        name: storage-volume
      - configMap:
          name: alertmanager
        name: alertmanager-config-volume
